In [1]:
import pandas as pd
import numpy as np

In [2]:
macro = pd.read_csv('./PredictorData2022.xlsx - Monthly.csv')
macro

,yyyymm,Index,D12,E12,b/m,tbl,AAA,BAA,lty,ntis,Rfree,infl,ltr,corpr,svar,csp,CRSP_SPvw,CRSP_SPvwx
0,187101,4.44,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,187102,4.50,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,0.004967,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,187103,4.61,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,0.004525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,187104,4.74,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,0.004252,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,187105,4.86,0.2600,0.4000,NaN,NaN,NaN,NaN,NaN,NaN,0.004643,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819,202208,"3,955.00",64.8854,188.8067,0.227429,0.0263,0.0407,0.0515,0.0290,-0.009732,0.001900,-0.000354,-0.0421,-0.0293,0.003349,NaN,-0.040305,-0.042052
1820,202209,"3,585.62",65.3183,187.0800,0.249478,0.0313,0.0459,0.0569,0.0352,-0.011292,0.001900,0.002151,-0.0769,-0.0526,0.004934,NaN,-0.091495,-0.092876
1821,202210,"3,871.98",65.8531,182.3033,0.218935,0.0372,0.0510,0.0626,0.0398,-0.015252,0.002300,0.004056,-0.0139,-0.0103,0.006504,NaN,0.080248,0.079196
1822,202211,"4,080.11",66.3880,177.5267,0.207182,0.0415,0.0490,0.0607,0.0389,-0.017011,0.002900,-0.001010,0.0268,0.0518,0.006343,NaN,0.054166,0.052158
1823,202212,"3,839.50",66.9228,172.7500,0.216199,0.0425,0.0443,0.0559,0.0362,-0.021246,0.003300,-0.003070,-0.0052,-0.0044,0.002701,NaN,-0.058784,-0.060170

In [3]:
for i in range(len(macro)):
    macro.Index.iloc[i] = macro.Index.iloc[i].replace(',', '')
macro.Index = np.array(macro.Index, dtype=float)

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_27903/2127312291.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  macro.Index.iloc[i] = macro.Index.iloc[i].replace(',', '')

In [4]:
macro['dp'] = np.log(macro.D12) - np.log(macro.Index)

In [5]:
macro['ep'] = np.log(macro.E12) - np.log(macro.Index)

In [6]:
macro['tms'] = macro.lty - macro.tbl

In [7]:
macro['dfy'] = macro.BAA - macro.AAA

In [8]:
macro_feature = macro[['yyyymm', 'dp', 'ep', 'b/m', 'ntis', 'tbl', 'tms', 'dfy', 'svar']]

In [9]:
macro_feature.to_pickle('./macro_feature.pkl')

In [10]:
macro_feature

,yyyymm,dp,ep,b/m,ntis,tbl,tms,dfy,svar
0,187101,-2.837728,-2.406945,NaN,NaN,NaN,NaN,NaN,NaN
1,187102,-2.851151,-2.420368,NaN,NaN,NaN,NaN,NaN,NaN
2,187103,-2.875302,-2.444519,NaN,NaN,NaN,NaN,NaN,NaN
3,187104,-2.903111,-2.472328,NaN,NaN,NaN,NaN,NaN,NaN
4,187105,-2.928112,-2.497329,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1819,202208,-4.110113,-3.042012,0.227429,-0.009732,0.0263,0.0027,0.0108,0.003349
1820,202209,-4.005414,-2.953150,0.249478,-0.011292,0.0313,0.0039,0.0110,0.004934
1821,202210,-4.074095,-3.055849,0.218935,-0.015252,0.0372,0.0026,0.0116,0.006504
1822,202211,-4.118363,-3.134758,0.207182,-0.017011,0.0415,-0.0026,0.0117,0.006343
1823,202212,-4.049558,-3.101252,0.216199,-0.021246,0.0425,-0.0063,0.0116,0.002701

In [ ]:
df = pd.read_pickle('./GKX_20201231.csv')
df

In [42]:
target = df[['permno', 'DATE', 'RET']]
target.to_pickle('./target.pkl')

In [11]:
del df['RET']
del df['prc']
del df['SHROUT']
del df['mve0']
del df['sic2']
df

,permno,DATE,mvel1,beta,betasq,chmom,dolvol,idiovol,indmom,mom1m,...,ms,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,bm,bm_ia
0,10006,19260130,6.540000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.006857,NaN,NaN,NaN,NaN,NaN,6.562500e-05,NaN,NaN
1,10022,19260130,1.120000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.018018,NaN,NaN,NaN,NaN,NaN,2.573529e-06,NaN,NaN
2,10030,19260130,2.340000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.004158,NaN,NaN,NaN,NaN,NaN,2.275000e-05,NaN,NaN
3,10049,19260130,1.850000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.006780,NaN,NaN,NaN,NaN,NaN,2.187500e-05,NaN,NaN
4,10057,19260130,6.125000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.071795,NaN,NaN,NaN,NaN,NaN,9.943182e-06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4345503,93423,20201231,2.611343e+06,1.921340,3.691548,0.798194,16.060575,0.061120,-0.149810,0.421369,...,6.0,0.060029,4.462048e-10,0.176471,0.050187,0.519033,17.649093,3.803709e-09,NaN,NaN
4345504,93426,20201231,3.671460e+05,1.301940,1.695047,0.551929,12.334190,0.043174,0.317594,0.224362,...,6.0,0.035050,2.296462e-08,0.159100,0.043004,0.473367,2.144264,3.236729e-08,NaN,NaN
4345505,93427,20201231,2.523235e+06,0.847169,0.717695,0.011311,14.568580,0.050471,0.606435,0.138121,...,4.0,0.029388,1.364274e-09,0.048227,0.020206,0.294512,1.469369,2.227010e-08,NaN,NaN
4345506,93434,20201231,8.738802e+04,0.389812,0.151954,0.282874,9.453983,0.073887,-0.144895,0.144737,...,3.0,0.051558,3.435272e-07,0.116667,0.035277,0.935967,0.897075,1.037670e-07,NaN,NaN
4345507,93436,20201231,1.735365e+08,1.349505,1.821163,0.868039,19.036016,0.083041,0.051465,0.462736,...,4.0,0.047931,1.820359e-12,0.101968,0.039271,0.531632,18.110463,2.654462e-09,NaN,NaN

In [45]:
df.to_pickle('./firm_feature.pkl')

In [7]:
df = pd.read_pickle('./firm_feature.pkl')

In [8]:
df.set_index('DATE', drop=True, inplace=True)

In [9]:
data_set = df.loc['19570101':'20170101']

In [14]:
macro_feature.set_index('yyyymm', drop=True, inplace=True)

In [15]:
data_macro_feature = macro_feature.loc['195701':'201701']

In [16]:
data_macro_feature

,dp,ep,b/m,ntis,tbl,tms,dfy,svar
yyyymm,,,,,,,,
195701,-3.248434,-2.574677,0.567243,0.027992,0.0311,0.0017,0.0072,0.000902
195702,-3.217201,-2.542483,0.584994,0.030173,0.0310,0.0018,0.0080,0.001056
195703,-3.238565,-2.562911,0.599819,0.026600,0.0308,0.0023,0.0077,0.000330
195704,-3.274852,-2.597229,0.576098,0.027421,0.0307,0.0038,0.0077,0.000302
195705,-3.311134,-2.631575,0.564039,0.028849,0.0306,0.0042,0.0078,0.000482
...,...,...,...,...,...,...,...,...
201609,-3.874451,-3.192038,0.316794,-0.032603,0.0029,0.0167,0.0090,0.001673
201610,-3.849850,-3.152198,0.319688,-0.029034,0.0033,0.0187,0.0087,0.000364
201611,-3.878496,-3.165980,0.303286,-0.027452,0.0045,0.0222,0.0085,0.000946
201612,-3.891597,-3.164580,0.293479,-0.025104,0.0051,0.0221,0.0077,0.000524
201701,-3.904362,-3.162272,0.291980,-0.022658,0.0051,0.0227,0.0074,0.000336

In [17]:
from tqdm import tqdm
train_dict = {}
for index in tqdm(data_set.index.unique()[500:]):
    cross_sec = data_set.loc[index]
    train_dict[index] = pd.DataFrame()
    # for col in cross_sec.columns[1:]:
    for col1 in data_macro_feature.columns:
        cs = np.array(data_macro_feature.loc[int(str(index)[:6]) ,col1]) * cross_sec.iloc[:, 1:]
        li = []
        for col in cs.columns:
            li.append(col+'_'+col1)
        # cs = pd.concat([cross_sec.permno, cs], axis=1)
        cs.columns=np.array(li)
        
        train_dict[index] = pd.concat([train_dict[index], cs], axis=1)
    train_dict[index] = pd.concat([cross_sec.permno, train_dict[index]], axis=1)

        #cross_sec[col+'_'+col1] = cross_sec[col] * data_macro_feature.loc[int(str(index)[:6]) ,col1]

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 220/220 [00:11<00:00, 19.70it/s]

In [16]:
train_data = pd.DataFrame()
for index in tqdm(data_set.index.unique()[360:500]):
    train_data = pd.concat([train_data, train_dict[index]], axis=0)
train_data

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 140/140 [04:36<00:00,  1.98s/it]

,permno,mvel1_dp,beta_dp,betasq_dp,chmom_dp,dolvol_dp,idiovol_dp,indmom_dp,mom1m_dp,mom6m_dp,...,ms_svar,baspread_svar,ill_svar,maxret_svar,retvol_svar,std_dolvol_svar,std_turn_svar,zerotrade_svar,bm_svar,bm_ia_svar
DATE,,,,,,,,,,,,,,,,,,,,,
19870130,10000,-6.929795e+03,NaN,NaN,NaN,-26.114282,NaN,-0.499732,1.319685,2.404301,...,NaN,0.000412,4.244311e-08,0.000248,0.000121,0.003628,0.017375,4.731161e-03,NaN,NaN
19870130,10001,-2.425983e+04,NaN,NaN,-0.753588,-26.889395,NaN,-1.110191,-0.052457,-0.565424,...,NaN,0.000109,2.461120e-08,0.000191,0.000097,0.002943,0.006920,1.655907e-02,NaN,NaN
19870130,10002,-5.085096e+04,NaN,NaN,0.449981,-28.434471,NaN,-0.499732,0.261470,-0.189502,...,NaN,0.000070,2.311234e-09,0.000025,0.000026,0.003235,0.003226,4.731162e-03,NaN,NaN
19870130,10003,-1.470951e+05,NaN,NaN,0.521298,-39.263406,NaN,-0.499732,0.172699,0.241184,...,NaN,0.000049,2.989595e-10,0.000093,0.000040,0.002889,0.021607,2.365581e-03,NaN,NaN
19870130,10005,-1.516677e+03,NaN,NaN,-1.002000,-16.516944,NaN,-0.499732,-0.000000,1.165722,...,NaN,0.001652,0.000000e+00,0.000000,0.000000,0.005014,0.000570,4.258045e-02,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19980831,93009,-1.531402e+05,-2.627554,-1.689433,0.356429,-48.488106,-0.376129,-1.020524,1.382233,1.221767,...,0.046670,0.000847,1.357215e-09,0.001127,0.000423,0.006712,0.045957,1.128027e-10,0.001830,-0.001642
19980831,93025,-1.546753e+04,-7.615590,-14.192043,-0.185755,-34.954643,-0.406207,0.202838,0.170275,-0.371509,...,NaN,0.001108,1.466657e-07,0.001436,0.001306,0.014753,0.064656,1.781930e-02,0.008189,0.004306
19980831,93105,-2.751426e+06,-2.725841,-1.818188,0.623313,-50.207966,-0.237033,-1.470905,0.197368,-1.402863,...,NaN,0.000492,1.886149e-10,0.000347,0.000240,0.006383,0.015351,3.964891e-10,0.001903,-0.002628
19980831,93236,-1.725107e+04,-9.763070,-23.324408,1.336559,-36.011643,-0.464892,-0.057649,0.583800,2.403883,...,0.018668,0.001445,1.180479e-07,0.003111,0.001328,0.010172,0.022984,2.638655e-10,-0.007906,-0.010692
19980831,93316,-8.388769e+04,-4.192433,-4.301007,-1.094027,-33.908364,-0.293061,0.322280,0.088200,-0.282918,...,0.018668,0.000234,1.200862e-08,0.000594,0.000202,0.012498,0.028816,6.236754e-02,0.009050,0.004260

In [18]:
train_data1 = pd.DataFrame()
for index in tqdm(data_set.index.unique()[500:600]):
    train_data1 = pd.concat([train_data1, train_dict[index]], axis=0)
train_data1

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100/100 [02:22<00:00,  1.42s/it]

,permno,mvel1_dp,beta_dp,betasq_dp,chmom_dp,dolvol_dp,idiovol_dp,indmom_dp,mom1m_dp,mom6m_dp,...,ms_svar,baspread_svar,ill_svar,maxret_svar,retvol_svar,std_dolvol_svar,std_turn_svar,zerotrade_svar,bm_svar,bm_ia_svar
DATE,,,,,,,,,,,,,,,,,,,,,
19980930,10001,-8.711461e+04,-0.745655,-0.134198,0.174762,-36.629822,-0.118299,-0.743780,-0.000000,-0.018836,...,0.009971,0.000209,1.137879e-08,0.000285,0.000213,0.011331,0.011951,5.982610e-02,0.007210,-0.000450
19980930,10002,-4.356010e+05,-2.817838,-1.916473,1.932802,-33.710396,-0.177683,-1.227560,0.681782,-0.528036,...,0.029913,0.000248,3.453030e-08,0.000997,0.000431,0.009133,0.001586,2.991306e-02,0.004358,-0.000479
19980930,10009,-1.941411e+05,-0.968090,-0.226205,0.827522,-40.425472,-0.129001,-1.227560,0.763975,0.185098,...,0.039884,0.000153,5.876385e-08,0.000401,0.000359,0.014586,0.006738,6.979712e-02,0.006310,0.001473
19980930,10012,-5.058769e+04,-9.310989,-20.924855,4.741047,-43.028739,-0.520574,0.836797,2.355901,2.071568,...,0.039884,0.001531,1.144351e-08,0.001466,0.000914,0.007849,0.039091,2.393278e-10,0.000939,-0.004204
19980930,10016,-7.456484e+05,-3.171927,-2.428383,-0.451161,-46.564968,-0.189362,0.536182,0.396300,-0.528047,...,0.009971,0.000266,7.518959e-10,0.000347,0.000215,0.009872,0.027782,3.531909e-10,0.003009,-0.001192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20061229,92690,-6.388052e+05,-0.828514,-0.169784,-0.116110,-41.288970,-0.078730,-0.947467,0.105469,-0.322090,...,0.001073,0.000005,2.177990e-11,0.000005,0.000004,0.000222,0.000184,4.001771e-11,0.000127,-0.000086
20061229,92807,-4.424389e+05,-1.418392,-0.497611,0.217055,-39.490212,-0.137764,-0.375284,-0.179413,0.218321,...,0.000358,0.000009,8.230704e-11,0.000007,0.000004,0.000339,0.000173,5.273200e-11,0.000312,0.000099
20061229,92874,-2.945549e+05,-0.398120,-0.039204,-0.891260,-36.213296,-0.213329,-0.367500,-0.032344,0.573605,...,0.001430,0.000010,1.486765e-10,0.000009,0.000004,0.000376,0.000288,7.025784e-11,0.000087,-0.000106
20061229,92930,-3.348818e+06,-4.402292,-4.793526,-0.466712,-55.301029,-0.110410,-1.046840,-0.168539,-1.083281,...,0.001788,0.000004,1.647440e-12,0.000007,0.000004,0.000241,0.001957,8.716558e-12,0.006069,-0.017881
20061229,93105,-4.083218e+06,-7.061480,-12.333571,0.316762,-52.441755,-0.148414,-0.375284,-0.330994,0.915902,...,0.001430,0.000012,2.381145e-12,0.000017,0.000007,0.000177,0.000424,1.299936e-11,0.000306,0.000094

In [19]:
train_data2 = pd.DataFrame()
for index in tqdm(data_set.index.unique()[600:]):
    train_data2 = pd.concat([train_data2, train_dict[index]], axis=0)
train_data2

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 120/120 [02:31<00:00,  1.26s/it]

,permno,mvel1_dp,beta_dp,betasq_dp,chmom_dp,dolvol_dp,idiovol_dp,indmom_dp,mom1m_dp,mom6m_dp,...,ms_svar,baspread_svar,ill_svar,maxret_svar,retvol_svar,std_dolvol_svar,std_turn_svar,zerotrade_svar,bm_svar,bm_ia_svar
DATE,,,,,,,,,,,,,,,,,,,,,
20070131,10001,-1.329829e+05,-2.241789,-1.241257,-1.261787,-36.631805,-0.247315,-0.902170,0.150996,-1.225494,...,0.001351,0.000007,4.996451e-09,0.000010,0.000006,0.000859,0.000384,7.310458e-11,0.000401,0.000071
20070131,10002,-1.153735e+06,-5.939346,-8.712634,0.336220,-46.662867,-0.143096,-0.427155,-0.240822,-0.147125,...,0.002252,0.000012,3.143441e-11,0.000017,0.000009,0.000353,0.000347,4.205065e-11,0.000264,-0.000005
20070131,10025,-1.702132e+06,-3.519258,-3.058964,-1.046022,-52.539953,-0.188076,-0.930079,-0.144741,-2.186747,...,0.001351,0.000014,4.959805e-12,0.000014,0.000008,0.000283,0.002095,9.557759e-12,0.000026,-0.000143
20070131,10026,-3.103501e+06,-4.671833,-5.390720,-0.563549,-52.474036,-0.127814,-0.788564,-0.338988,-0.649171,...,0.002252,0.000011,2.038359e-12,0.000027,0.000008,0.000168,0.000682,1.361253e-11,0.000209,-0.000051
20070131,10028,-5.052523e+04,-2.636468,-1.716790,0.559723,-42.643318,-0.322728,-0.667099,-0.131669,-0.118584,...,0.000450,0.000025,2.487755e-09,0.000045,0.000020,0.000570,0.001012,3.403636e-11,0.000280,0.000071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20161230,93428,-4.868295e+06,-6.224316,-9.955324,0.534504,-58.047881,-0.168140,-0.067953,0.004683,0.182976,...,0.003144,0.000015,5.293742e-13,0.000014,0.000009,0.000257,0.002802,4.540541e-12,0.000133,-0.000101
20161230,93429,-2.179503e+07,-1.163424,-0.347815,-0.803356,-63.507716,-0.101955,0.341831,-0.365703,-0.000555,...,0.003144,0.000008,5.730028e-14,0.000021,0.000005,0.000283,0.003277,4.336354e-12,0.000026,-0.000268
20161230,93433,-9.626352e+04,-9.070880,-21.143212,-1.277411,-38.819492,-0.755756,0.021862,-1.086027,1.394005,...,0.001048,0.000078,2.038430e-10,0.000212,0.000072,0.000674,0.015238,2.627550e-12,-0.000694,-0.000985
20161230,93434,-3.336375e+05,-2.453392,-1.546699,-0.081156,-42.271292,-0.232698,-0.059103,0.192653,-0.427648,...,0.001572,0.000022,4.494506e-11,0.000017,0.000010,0.000330,0.001274,1.843820e-11,0.000439,0.000128
20161230,93436,-1.105337e+08,-6.196984,-9.868084,0.470950,-72.309229,-0.194282,-0.172027,0.163946,0.444545,...,0.002096,0.000018,9.715266e-15,0.000019,0.000011,0.000161,0.005158,1.655707e-12,0.000018,-0.000205

In [20]:
train_data.to_pickle('./test1.pkl')
train_data1.to_pickle('./test2.pkl')
train_data2.to_pickle('./test3.pkl')

In [1]:

train_data = pd.read_pickle('./test1.pkl')
train_data1= pd.read_pickle('./test2.pkl')
train_data2= pd.read_pickle('./test3.pkl')

In [2]:
test1 = pd.concat([train_data, train_data1], axis=0)

In [3]:
test1.to_pickle('./test_data1.pkl')

In [4]:
test2 = pd.concat([test1, train_data2],axis=0)

In [5]:
test2

,permno,mvel1_dp,beta_dp,betasq_dp,chmom_dp,dolvol_dp,idiovol_dp,indmom_dp,mom1m_dp,mom6m_dp,...,ms_svar,baspread_svar,ill_svar,maxret_svar,retvol_svar,std_dolvol_svar,std_turn_svar,zerotrade_svar,bm_svar,bm_ia_svar
DATE,,,,,,,,,,,,,,,,,,,,,
19870130,10000,-6.929795e+03,NaN,NaN,NaN,-26.114282,NaN,-0.499732,1.319685,2.404301,...,NaN,0.000412,4.244311e-08,0.000248,0.000121,0.003628,0.017375,4.731161e-03,NaN,NaN
19870130,10001,-2.425983e+04,NaN,NaN,-0.753588,-26.889395,NaN,-1.110191,-0.052457,-0.565424,...,NaN,0.000109,2.461120e-08,0.000191,0.000097,0.002943,0.006920,1.655907e-02,NaN,NaN
19870130,10002,-5.085096e+04,NaN,NaN,0.449981,-28.434471,NaN,-0.499732,0.261470,-0.189502,...,NaN,0.000070,2.311234e-09,0.000025,0.000026,0.003235,0.003226,4.731162e-03,NaN,NaN
19870130,10003,-1.470951e+05,NaN,NaN,0.521298,-39.263406,NaN,-0.499732,0.172699,0.241184,...,NaN,0.000049,2.989595e-10,0.000093,0.000040,0.002889,0.021607,2.365581e-03,NaN,NaN
19870130,10005,-1.516677e+03,NaN,NaN,-1.002000,-16.516944,NaN,-0.499732,-0.000000,1.165722,...,NaN,0.001652,0.000000e+00,0.000000,0.000000,0.005014,0.000570,4.258045e-02,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20161230,93428,-4.868295e+06,-6.224316,-9.955324,0.534504,-58.047881,-0.168140,-0.067953,0.004683,0.182976,...,0.003144,0.000015,5.293742e-13,0.000014,0.000009,0.000257,0.002802,4.540541e-12,0.000133,-0.000101
20161230,93429,-2.179503e+07,-1.163424,-0.347815,-0.803356,-63.507716,-0.101955,0.341831,-0.365703,-0.000555,...,0.003144,0.000008,5.730028e-14,0.000021,0.000005,0.000283,0.003277,4.336354e-12,0.000026,-0.000268
20161230,93433,-9.626352e+04,-9.070880,-21.143212,-1.277411,-38.819492,-0.755756,0.021862,-1.086027,1.394005,...,0.001048,0.000078,2.038430e-10,0.000212,0.000072,0.000674,0.015238,2.627550e-12,-0.000694,-0.000985
20161230,93434,-3.336375e+05,-2.453392,-1.546699,-0.081156,-42.271292,-0.232698,-0.059103,0.192653,-0.427648,...,0.001572,0.000022,4.494506e-11,0.000017,0.000010,0.000330,0.001274,1.843820e-11,0.000439,0.000128
20161230,93436,-1.105337e+08,-6.196984,-9.868084,0.470950,-72.309229,-0.194282,-0.172027,0.163946,0.444545,...,0.002096,0.000018,9.715266e-15,0.000019,0.000011,0.000161,0.005158,1.655707e-12,0.000018,-0.000205

In [6]:
test2.to_pickle('./test_data2.pkl')

In [1]:
import pandas as pd
import numpy as np
test2 = pd.read_pickle('./test_data2.pkl')

In [2]:
df = pd.read_pickle('./firm_feature.pkl')
df.set_index('DATE', drop=True, inplace=True)
data_set = df.loc['19570101':'20170101']

In [3]:
all_data = pd.concat([test2, data_set.loc['19870101':'20170101', data_set.columns[1:]]], axis=1)

In [4]:
all_data

,permno,mvel1_dp,beta_dp,betasq_dp,chmom_dp,dolvol_dp,idiovol_dp,indmom_dp,mom1m_dp,mom6m_dp,...,ms,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,bm,bm_ia
DATE,,,,,,,,,,,,,,,,,,,,,
19870130,10000,-6.929795e+03,NaN,NaN,NaN,-26.114282,NaN,-0.499732,1.319685,2.404301,...,NaN,0.166424,1.712640e-05,0.100000,0.048899,1.463823,7.011243,1.909091e+00,NaN,NaN
19870130,10001,-2.425983e+04,NaN,NaN,-0.753588,-26.889395,NaN,-1.110191,-0.052457,-0.565424,...,NaN,0.043835,9.930969e-06,0.076923,0.039045,1.187689,2.792165,6.681818e+00,NaN,NaN
19870130,10002,-5.085096e+04,NaN,NaN,0.449981,-28.434471,NaN,-0.499732,0.261470,-0.189502,...,NaN,0.028054,9.326158e-07,0.010101,0.010519,1.305555,1.301610,1.909091e+00,NaN,NaN
19870130,10003,-1.470951e+05,NaN,NaN,0.521298,-39.263406,NaN,-0.499732,0.172699,0.241184,...,NaN,0.019699,1.206344e-07,0.037500,0.015984,1.165881,8.718616,9.545455e-01,NaN,NaN
19870130,10005,-1.516677e+03,NaN,NaN,-1.002000,-16.516944,NaN,-0.499732,-0.000000,1.165722,...,NaN,0.666667,0.000000e+00,0.000000,0.000000,2.023175,0.230187,1.718182e+01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20161230,93428,-4.868295e+06,-6.224316,-9.955324,0.534504,-58.047881,-0.168140,-0.067953,0.004683,0.182976,...,6.0,0.029302,1.010214e-09,0.027604,0.017847,0.490189,5.347476,8.664791e-09,0.252853,-0.192059
20161230,93429,-2.179503e+07,-1.163424,-0.347815,-0.803356,-63.507716,-0.101955,0.341831,-0.365703,-0.000555,...,6.0,0.016001,1.093471e-10,0.040887,0.010437,0.539155,6.252920,8.275139e-09,0.049733,-0.512336
20161230,93433,-9.626352e+04,-9.070880,-21.143212,-1.277411,-38.819492,-0.755756,0.021862,-1.086027,1.394005,...,2.0,0.149511,3.889972e-07,0.405473,0.137955,1.285707,29.078756,5.014198e-09,-1.324437,-1.879364
20161230,93434,-3.336375e+05,-2.453392,-1.546699,-0.081156,-42.271292,-0.232698,-0.059103,0.192653,-0.427648,...,3.0,0.042877,8.576942e-08,0.031579,0.019838,0.629682,2.431419,3.518593e-08,0.837790,0.244711
20161230,93436,-1.105337e+08,-6.196984,-9.868084,0.470950,-72.309229,-0.194282,-0.172027,0.163946,0.444545,...,4.0,0.034094,1.853981e-11,0.036039,0.021170,0.307665,9.842282,3.159615e-09,0.034522,-0.392109

In [7]:
all_data.to_pickle('./test_data.pkl')

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./GKX_20201231.csv')
df.set_index('DATE', drop=True, inplace=True)
data_set = df.loc['19570101':'20170101']

In [3]:
sic_data = data_set[['permno', 'sic2']]

In [4]:
industry = data_set.sic2.unique()
industry = industry[~np.isnan(industry)]

In [5]:
industry_var = pd.DataFrame(0, index=data_set.index, columns=industry)
from tqdm import trange
for i in trange(len(sic_data)):
    if np.isnan(sic_data.iloc[i, 1]):
        continue
    else:
        num = sic_data.iloc[i, 1]
        idx = industry.tolist().index(num)
        industry_var.iloc[i, idx] = 1

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3762139/3762139 [02:31<00:00, 24862.64it/s]

In [6]:
industry_var.to_pickle('./industry_var.pkl')

In [38]:
train_data = pd.read_pickle('./train_data.pkl')

In [39]:
train_data = pd.concat([train_data, industry_var.loc['19570101':'19750101']], axis=1)

In [41]:
train_data.to_pickle('./train_data_with_ind.pkl')

In [45]:
val_data = pd.read_pickle('./val_data.pkl')
val_data = pd.concat([val_data, industry_var.loc['19750101':'19870101']], axis=1)
val_data.to_pickle('./val_data_with_ind.pkl')

In [1]:
import pandas as pd
import numpy as np
test_data = pd.read_pickle('./test_data_with_ind.pkl')

In [7]:
test_data = pd.read_pickle('./test_data.pkl')
test_data = pd.concat([test_data, industry_var.loc['19870101':'20170101']], axis=1)
test_data.to_pickle('./test_data_with_ind.pkl')

In [43]:
industry_var.loc['19750101':'19870101']

,37.0,28.0,49.0,13.0,33.0,27.0,48.0,63.0,42.0,35.0,...,8.0,2.0,41.0,84.0,83.0,46.0,89.0,81.0,9.0,86.0
DATE,,,,,,,,,,,,,,,,,,,,,
19750131,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19750131,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19750131,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19750131,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19750131,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19861231,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19861231,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19861231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19861231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19861231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
test_data

,permno,mvel1_dp,beta_dp,betasq_dp,chmom_dp,dolvol_dp,idiovol_dp,indmom_dp,mom1m_dp,mom6m_dp,...,8.0,2.0,41.0,84.0,83.0,46.0,89.0,81.0,9.0,86.0
DATE,,,,,,,,,,,,,,,,,,,,,
19870130,10000,-6.929795e+03,NaN,NaN,NaN,-26.114282,NaN,-0.499732,1.319685,2.404301,...,0,0,0,0,0,0,0,0,0,0
19870130,10001,-2.425983e+04,NaN,NaN,-0.753588,-26.889395,NaN,-1.110191,-0.052457,-0.565424,...,0,0,0,0,0,0,0,0,0,0
19870130,10002,-5.085096e+04,NaN,NaN,0.449981,-28.434471,NaN,-0.499732,0.261470,-0.189502,...,0,0,0,0,0,0,0,0,0,0
19870130,10003,-1.470951e+05,NaN,NaN,0.521298,-39.263406,NaN,-0.499732,0.172699,0.241184,...,0,0,0,0,0,0,0,0,0,0
19870130,10005,-1.516677e+03,NaN,NaN,-1.002000,-16.516944,NaN,-0.499732,-0.000000,1.165722,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20161230,93428,-4.868295e+06,-6.224316,-9.955324,0.534504,-58.047881,-0.168140,-0.067953,0.004683,0.182976,...,0,0,0,0,0,0,0,0,0,0
20161230,93429,-2.179503e+07,-1.163424,-0.347815,-0.803356,-63.507716,-0.101955,0.341831,-0.365703,-0.000555,...,0,0,0,0,0,0,0,0,0,0
20161230,93433,-9.626352e+04,-9.070880,-21.143212,-1.277411,-38.819492,-0.755756,0.021862,-1.086027,1.394005,...,0,0,0,0,0,0,0,0,0,0
20161230,93434,-3.336375e+05,-2.453392,-1.546699,-0.081156,-42.271292,-0.232698,-0.059103,0.192653,-0.427648,...,0,0,0,0,0,0,0,0,0,0
20161230,93436,-1.105337e+08,-6.196984,-9.868084,0.470950,-72.309229,-0.194282,-0.172027,0.163946,0.444545,...,0,0,0,0,0,0,0,0,0,0

In [2]:
test_data1 = test_data.iloc[:, :847]

In [3]:
test_data1.reset_index(inplace=True)

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_86673/654080452.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_data1.reset_index(inplace=True)

In [4]:
test_data1.set_index(['DATE', 'permno'], inplace=True)

In [ ]:
test_data1.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

In [ ]:
test_data = pd.concat([test_data1, test_data.iloc[:, 847:]], axis=1)

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_86221/2992580283.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_data1.reset_index(inplace=True)

In [1]:
import pandas as pd
import numpy as np
train_data = pd.read_pickle('./train_data_with_ind.pkl')
train_data.reset_index(inplace=True)
train_data.set_index(['DATE', 'permno'], inplace=True)
train_data.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

                      mvel1_dp   beta_dp  betasq_dp  chmom_dp  dolvol_dp  \
DATE     permno
19570131 10006  -267180.453665 -3.647493  -4.095574 -0.153259 -31.087363
         10014   -12679.856330 -1.386219  -0.591547  0.895402 -20.263200
         10022   -30123.541222 -3.464289  -3.694487  0.082802 -22.767768
         10030  -176928.803898 -3.008174  -2.785685 -0.059028 -31.916959
         10057  -130749.471240 -4.053227  -5.057405 -0.083761 -25.665900
...                        ...       ...        ...       ...        ...
19741231 84794  -184187.461485 -3.846644  -5.021308  3.189384 -23.265528
         84903    -4620.543872 -2.811372  -2.682190  0.433370 -23.265528
         85682   -14207.141036 -3.983325  -5.384488  0.423090 -21.967386
         92946    -6600.776961 -0.104120  -0.003679  0.321466 -19.139532
         93172   -22656.651231 -3.060130  -3.177846  1.030009 -24.091606

                 idiovol_dp  indmom_dp  mom1m_dp  mom6m_dp  mom12m_dp  ...  \
DATE     permno                                                        ...
19570131 10006    -0.083620  -0.150069 -0.145670  0.193336   0.390457  ...
         10014    -0.226127  -0.150069  0.282473  0.374819   0.135351  ...
         10022    -0.089813  -0.150069  0.196132  0.128476   0.353269  ...
         10030    -0.070493  -0.150069 -0.144987 -0.163948  -0.434154  ...
         10057    -0.082856  -0.150069 -0.281531 -0.179466  -0.593957  ...
...                     ...        ...       ...       ...        ...  ...
19741231 84794    -0.392976   1.001460  0.743846  0.731316  -1.211004  ...
         84903    -0.164083   0.731820  0.368347  0.516263   0.692446  ...
         85682    -0.183513   0.802930  0.873119  1.976496   2.582644  ...
         92946    -0.188045   0.802930  0.196452  1.942193   2.517545  ...
         93172    -0.204665   0.802930  0.471484  2.238416   2.556143  ...

                 8.0  2.0  41.0  84.0  83.0  46.0  89.0  81.0  9.0  86.0
DATE     permno
19570131 10006     0    0     0     0     0     0     0     0    0     0
         10014     0    0     0     0     0     0     0     0    0     0
         10022     0    0     0     0     0     0     0     0    0     0
         10030     0    0     0     0     0     0     0     0    0     0
         10057     0    0     0     0     0     0     0     0    0     0
...              ...  ...   ...   ...   ...   ...   ...   ...  ...   ...
19741231 84794     0    0     0     0     0     0     0     0    0     0
         84903     0    0     0     0     0     0     0     0    0     0
         85682     0    0     0     0     0     0     0     0    0     0
         92946     0    0     0     0     0     0     0     0    0     0
         93172     0    0     0     0     0     0     0     0    0     0

[479467 rows x 920 columns]

In [2]:
train_data_fillna = train_data.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))
train_data_fillna.to_pickle('./train_data_with_ind.pkl')

In [3]:
import pandas as pd
import numpy as np
val_data = pd.read_pickle('./val_data_with_ind.pkl')
val_data.reset_index(inplace=True)
val_data.set_index(['DATE', 'permno'], inplace=True)
val_data_fillna = val_data.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

In [5]:
val_data_fillna.to_pickle('./val_data_with_ind.pkl')

In [1]:
import pandas as pd
import numpy as np
test_data = pd.read_pickle('./test_data_with_ind.pkl')

In [3]:
test1 = test_data.iloc[:500000]
test1.reset_index(inplace=True)
test1.set_index(['DATE', 'permno'], inplace=True)
test1 = test1.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_87806/2374082107.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test1.reset_index(inplace=True)

In [5]:
test2 = test_data.iloc[500000:1000000]
test2.reset_index(inplace=True)
test2.set_index(['DATE', 'permno'], inplace=True)
test2 = test2.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_87806/1829732541.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test2.reset_index(inplace=True)

In [6]:
test3 = test_data.iloc[1000000:1500000]
test3.reset_index(inplace=True)
test3.set_index(['DATE', 'permno'], inplace=True)
test3 = test3.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_87806/1187298742.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test3.reset_index(inplace=True)

In [7]:
test4 = test_data.iloc[1500000:2000000]
test4.reset_index(inplace=True)
test4.set_index(['DATE', 'permno'], inplace=True)
test4 = test4.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_87806/3781460127.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test4.reset_index(inplace=True)

In [8]:
test5 = test_data.iloc[2000000:]
test5.reset_index(inplace=True)
test5.set_index(['DATE', 'permno'], inplace=True)
test5 = test5.groupby('DATE', group_keys=True).apply(lambda x: x.fillna(x.median()))

/var/folders/rp/8c0pvywd07x0n19dc5yqt8fw0000gn/T/ipykernel_87806/3229019649.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test5.reset_index(inplace=True)

In [9]:
test1.to_pickle('./test1_fillna.pkl')
test2.to_pickle('./test2_fillna.pkl')
test3.to_pickle('./test3_fillna.pkl')
test4.to_pickle('./test4_fillna.pkl')
test5.to_pickle('./test5_fillna.pkl')

In [1]:
import pandas as pd
test1 = pd.read_pickle('./test1_fillna.pkl')
test2 = pd.read_pickle('./test2_fillna.pkl')
test3 = pd.read_pickle('./test3_fillna.pkl')

In [2]:
test_123 = pd.concat([test1, test2, test3], axis=0)
test_123.to_pickle('./test123.pkl')

In [1]:
import pandas as pd
test123 = pd.read_pickle('./test123.pkl')

In [2]:
test4 = pd.read_pickle('./test4_fillna.pkl')
test5 = pd.read_pickle('./test5_fillna.pkl')

In [4]:
test_data_fillna = pd.concat([test123, test4, test5], axis=0)
test_data_fillna.to_pickle('./test_data_with_ind.pkl')

In [5]:
test_data_fillna

                     mvel1_dp   beta_dp  betasq_dp  chmom_dp  dolvol_dp  \
DATE     permno
19870130 10000  -6.929795e+03 -3.433943  -3.388857  1.032896 -26.114282
         10001  -2.425983e+04 -3.433943  -3.388857 -0.753588 -26.889395
         10002  -5.085096e+04 -3.433943  -3.388857  0.449981 -28.434471
         10003  -1.470951e+05 -3.433943  -3.388857  0.521298 -39.263406
         10005  -1.516677e+03 -3.433943  -3.388857 -1.002000 -16.516944
...                       ...       ...        ...       ...        ...
20161230 93428  -4.868295e+06 -6.224316  -9.955324  0.534504 -58.047881
         93429  -2.179503e+07 -1.163424  -0.347815 -0.803356 -63.507716
         93433  -9.626352e+04 -9.070880 -21.143212 -1.277411 -38.819492
         93434  -3.336375e+05 -2.453392  -1.546699 -0.081156 -42.271292
         93436  -1.105337e+08 -6.196984  -9.868084  0.470950 -72.309229

                 idiovol_dp  indmom_dp  mom1m_dp  mom6m_dp  mom12m_dp  ...  \
DATE     permno                                                        ...
19870130 10000    -0.179839  -0.499732  1.319685  2.404301  -0.277950  ...
         10001    -0.179839  -1.110191 -0.052457 -0.565424  -0.417628  ...
         10002    -0.179839  -0.499732  0.261470 -0.189502  -0.573061  ...
         10003    -0.179839  -0.499732  0.172699  0.241184   0.130088  ...
         10005    -0.179839  -0.499732 -0.000000  1.165722   2.610869  ...
...                     ...        ...       ...       ...        ...  ...
20161230 93428    -0.168140  -0.067953  0.004683  0.182976  -0.147770  ...
         93429    -0.101955   0.341831 -0.365703 -0.000555   0.436554  ...
         93433    -0.755756   0.021862 -1.086027  1.394005   2.661166  ...
         93434    -0.232698  -0.059103  0.192653 -0.427648  -0.574895  ...
         93436    -0.194282  -0.172027  0.163946  0.444545   0.549786  ...

                 8.0  2.0  41.0  84.0  83.0  46.0  89.0  81.0  9.0  86.0
DATE     permno
19870130 10000     0    0     0     0     0     0     0     0    0     0
         10001     0    0     0     0     0     0     0     0    0     0
         10002     0    0     0     0     0     0     0     0    0     0
         10003     0    0     0     0     0     0     0     0    0     0
         10005     0    0     0     0     0     0     0     0    0     0
...              ...  ...   ...   ...   ...   ...   ...   ...  ...   ...
20161230 93428     0    0     0     0     0     0     0     0    0     0
         93429     0    0     0     0     0     0     0     0    0     0
         93433     0    0     0     0     0     0     0     0    0     0
         93434     0    0     0     0     0     0     0     0    0     0
         93436     0    0     0     0     0     0     0     0    0     0

[2508785 rows x 920 columns]